apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: us.gcr.io/bdc-backend/api:latest
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        ports:
        - name: http
          containerPort: 9001
          protocol: TCP
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-atlas-login
              key: user
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-atlas-login
              key: password
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongo-atlas-login
              key: uri