apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: status
  labels:
    app: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
    spec:
      containers:
      - name: status
        image: google/nodejs-hello
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP