version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker CLI
          command: apk update && apk add docker
      - run:
          name: Build Image
          command: docker build --rm=false -t us.gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_SHA1 .
  test:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Run Tests
          command: pytest -W ignore::DeprecationWarning
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate to Google Cloud
          command: scripts/auth.sh
      - run:
          name: Connect Docker and Google Cloud
          command: gcloud auth configure-docker
      - run:
          name: Build Image
          command: scripts/build.sh
      - run: 
          name: Push Image to GCR
          command: scripts/deploy.sh
  update-k8s:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate to Google Cloud
          command: scripts/auth.sh
      - run:
          name: Update Kubernetes Configuration
          command: scripts/update-k8s.sh


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
          requires:
            - build
      - deploy
          requires:
            - build
            - test
      - update-k8s:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
                - api-status-integration