version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker CLI
          command: apk update && apk add docker-ce
      - run:
          name: Build Image
          command: docker build --rm=false -t us.gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_SHA1 .
  test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: apk add grep
      - run:
          name: Validate index.html
          command: scripts/test.sh
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up Google Cloud
          command: scripts/auth.sh
      - run:
          name: Build Image
          command: scripts/build.sh
      - run: 
          name: Push Image to GCR
          command: scripts/deploy.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test