version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run: scripts/auth.sh  # Authenticate to Google Cloud
      - run: apt-get update && apt-get install docker  # Install docker
      - run: docker build --rm=false -t us.gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_SHA1 .  # Build image
      - run: gcloud docker -- push us.gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_SHA1  # Deploy image

workflows:
  version: 2
  you_had_one_job:
    jobs:
      - deploy:
          filters:
            branches:
              only: daniel