apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-router
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 4000