apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-router
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bdc-kubernetes
    gke.googleapis.com/managed-certificates: gtbigdata-certificate
spec:
  rules:
  - host: gtbigdata.club
    http:
      paths:
      - path: /*
        backend:
          serviceName: website
          servicePort: 4000
      - path: /api/*
        backend:
          serviceName: api
          servicePort: 4001
      - path: /status/*
        backend:
          serviceName: status
          servicePort: 4002