apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-router
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bdc-kubernetes
spec:
  rules:
  - host: gtbigdata.club
    http:
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 4000
  - host: api.gtbigdata.club
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 4000
  - host: status.gtbigdata.club
    http:
      paths:
      - path: /
        backend:
          serviceName: status
          servicePort: 4000